---
language: python
before_install:
  - npm install stylus@0.27.2; npm install nib@0.5.0
install:
  - pip install coveralls
python:
  - "3.4"

# --source specifies what packages to cover, you probably want to use that option
script:
    coverage run --source=pacific setup.py test

after_success: coveralls
